import { BriefingTypeConfig } from "@/types/briefing";

export const ecommerceConfig: BriefingTypeConfig = {
    id: "ecommerce",
    type: "ECOMMERCE",
    label: "E-commerce",
    description: "Tienda online completa con carrito de compras, pagos y envíos",
    icon: "ShoppingCart",
    enabled: true,
    steps: [
        // ═══════════════════════════════════════════════════════
        // PASO 1 — Identidad / Contacto
        // ═══════════════════════════════════════════════════════
        {
            id: "identity",
            title: "Tu Negocio",
            description: "Cuéntanos sobre ti y tu tienda online",
            icon: "Store",
            fields: [
                {
                    id: "clientName",
                    label: "Tu nombre y apellido",
                    type: "text",
                    placeholder: "Ej: María González",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "businessName",
                    label: "Nombre de tu tienda o marca",
                    type: "text",
                    placeholder: "Ej: Tienda Moda Chile",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "industry",
                    label: "Rubro de tu tienda",
                    type: "select",
                    required: true,
                    dataGroup: "contact",
                    options: [
                        { value: "moda_vestuario", label: "Moda / Vestuario / Calzado" },
                        { value: "alimentos_bebidas", label: "Alimentos y Bebidas" },
                        { value: "tecnologia_electronica", label: "Tecnología / Electrónica" },
                        { value: "belleza_cosmeticos", label: "Belleza / Cosméticos" },
                        { value: "deportes", label: "Deportes / Fitness" },
                        { value: "hogar_decoracion", label: "Hogar / Decoración / Muebles" },
                        { value: "juguetes", label: "Juguetes / Infantil" },
                        { value: "mascotas", label: "Mascotas" },
                        { value: "libros_papeleria", label: "Libros / Papelería" },
                        { value: "joyeria_accesorios", label: "Joyería / Accesorios" },
                        { value: "salud", label: "Salud / Bienestar" },
                        { value: "automotriz", label: "Automotriz / Repuestos" },
                        { value: "gastronomia", label: "Gastronomía / Restaurante" },
                        { value: "productos_digitales", label: "Productos Digitales (cursos, ebooks...)" },
                        { value: "otro", label: "Otro" },
                    ],
                },
                {
                    id: "email",
                    label: "Correo electrónico de contacto",
                    type: "email",
                    placeholder: "Ej: contacto@mitienda.cl",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "phone",
                    label: "Teléfono / WhatsApp",
                    type: "tel",
                    placeholder: "Ej: +56 9 1234 5678",
                    required: false,
                    dataGroup: "contact",
                },
                {
                    id: "instagramUrl",
                    label: "Instagram (opcional)",
                    type: "text",
                    placeholder: "Ej: @mitienda o instagram.com/mitienda",
                    required: false,
                    dataGroup: "contact",
                    helperText: "Tu perfil de Instagram para integrar en la tienda",
                },
                {
                    id: "facebookUrl",
                    label: "Facebook (opcional)",
                    type: "text",
                    placeholder: "Ej: facebook.com/mitienda",
                    required: false,
                    dataGroup: "contact",
                    helperText: "Tu página de Facebook",
                },
                {
                    id: "websiteUrl",
                    label: "Sitio web actual (si tienes)",
                    type: "url",
                    placeholder: "Ej: https://mitienda.cl",
                    required: false,
                    dataGroup: "contact",
                    helperText: "Si ya tienes un sitio web o tienda online anterior",
                },
            ],
        },

        // ═══════════════════════════════════════════════════════
        // PASO 2 — Objetivo de la Tienda
        // ═══════════════════════════════════════════════════════
        {
            id: "objective",
            title: "Objetivo de la Tienda",
            description: "¿Qué quieres lograr con tu tienda online?",
            icon: "Target",
            fields: [
                {
                    id: "storeObjective",
                    label: "Objetivo principal de tu tienda",
                    type: "select",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "vender_online", label: "Comenzar a vender por internet" },
                        { value: "expandir_canal", label: "Agregar un canal de venta digital a mi negocio físico" },
                        { value: "reemplazar_tienda_fisica", label: "Migrar de tienda física a 100% online" },
                        { value: "lanzar_marca", label: "Lanzar una marca nueva directamente online" },
                        { value: "dropshipping", label: "Armar un negocio de dropshipping" },
                        { value: "marketplace_propio", label: "Crear mi propio marketplace / multi-vendedor" },
                    ],
                },
                {
                    id: "targetAudience",
                    label: "¿Quién es tu cliente ideal?",
                    type: "textarea",
                    placeholder: "Ej: Mujeres de 25-45 años que buscan ropa sustentable, nivel socioeconómico medio-alto...",
                    required: true,
                    dataGroup: "content",
                    helperText: "Describe edad, género, intereses, ubicación, poder adquisitivo",
                },
                {
                    id: "competitorUrls",
                    label: "¿Tienes tiendas de referencia o competidores?",
                    type: "textarea",
                    placeholder: "Ej: falabella.com, ripley.com, una tienda que te guste...",
                    required: false,
                    dataGroup: "content",
                    helperText: "URLs de tiendas que te gusten o que sean tu competencia",
                },
                {
                    id: "uniqueValue",
                    label: "¿Qué hace única a tu tienda?",
                    type: "textarea",
                    placeholder: "Ej: Productos artesanales hechos a mano, envío mismo día en Santiago...",
                    required: true,
                    dataGroup: "content",
                    helperText: "Tu diferenciador frente a la competencia",
                },
                {
                    id: "expectedRevenue",
                    label: "Facturación mensual esperada (CLP)",
                    type: "select",
                    required: false,
                    dataGroup: "content",
                    helperText: "Esto nos ayuda a dimensionar la infraestructura necesaria",
                    options: [
                        { value: "bajo_1m", label: "Menos de $1.000.000" },
                        { value: "1m_5m", label: "$1.000.000 – $5.000.000" },
                        { value: "5m_15m", label: "$5.000.000 – $15.000.000" },
                        { value: "15m_plus", label: "Más de $15.000.000" },
                    ],
                },
            ],
        },

        // ═══════════════════════════════════════════════════════
        // PASO 3 — Catálogo y Productos
        // ═══════════════════════════════════════════════════════
        {
            id: "catalog",
            title: "Catálogo y Productos",
            description: "Cuéntanos sobre lo que vas a vender",
            icon: "Package",
            fields: [
                {
                    id: "productCount",
                    label: "¿Cuántos productos vas a tener aproximadamente?",
                    type: "select",
                    required: true,
                    dataGroup: "content",
                    helperText: "Esto afecta la complejidad de navegación, filtros y búsqueda",
                    options: [
                        { value: "1_20", label: "1 a 20 productos" },
                        { value: "21_50", label: "21 a 50 productos" },
                        { value: "51_200", label: "51 a 200 productos" },
                        { value: "201_500", label: "201 a 500 productos" },
                        { value: "500_plus", label: "Más de 500 productos" },
                    ],
                },
                {
                    id: "productType",
                    label: "¿Qué tipo de productos vendes?",
                    type: "multiselect",
                    required: true,
                    dataGroup: "content",
                    helperText: "Puedes seleccionar más de uno",
                    options: [
                        { value: "fisicos", label: "Productos físicos" },
                        { value: "digitales", label: "Productos digitales (ebooks, cursos, software...)" },
                        { value: "servicios_digitales", label: "Servicios" },
                        { value: "suscripciones", label: "Suscripciones / Membresías" },
                        { value: "personalizados", label: "Productos personalizados (a medida)" },
                    ],
                },
                {
                    id: "hasVariants",
                    label: "¿Tus productos tienen variantes (tallas, colores, etc.)?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, la mayoría tiene variantes" },
                        { value: "algunos", label: "Solo algunos productos" },
                        { value: "no", label: "No, son productos simples" },
                    ],
                },
                {
                    id: "categoryCount",
                    label: "¿Cuántas categorías de productos tienes?",
                    type: "select",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "1_3", label: "1 a 3 categorías" },
                        { value: "4_10", label: "4 a 10 categorías" },
                        { value: "11_30", label: "11 a 30 categorías" },
                        { value: "30_plus", label: "Más de 30 categorías" },
                    ],
                },
                {
                    id: "productDescription",
                    label: "Describe brevemente tu catálogo",
                    type: "textarea",
                    placeholder: "Ej: Vendemos zapatillas deportivas importadas, con 50 modelos en 5 categorías...",
                    required: false,
                    dataGroup: "content",
                    helperText: "Cuéntanos más sobre tus productos para entender mejor tu negocio",
                },
                {
                    id: "hasBulkImport",
                    label: "¿Necesitas importar productos masivamente?",
                    type: "radio",
                    required: false,
                    dataGroup: "content",
                    helperText: "Importación desde Excel/CSV para subir muchos productos a la vez",
                    options: [
                        { value: "si", label: "Sí, tengo muchos productos" },
                        { value: "no", label: "No, los cargo manualmente" },
                        { value: "no_se", label: "No estoy seguro" },
                    ],
                },
            ],
        },

        // ═══════════════════════════════════════════════════════
        // PASO 4 — Páginas del Sitio
        // ═══════════════════════════════════════════════════════
        {
            id: "pages",
            title: "Páginas del Sitio",
            description: "¿Qué páginas necesita tu tienda online?",
            icon: "Layout",
            fields: [
                {
                    id: "pages",
                    label: "Selecciona las páginas que deseas",
                    type: "multiselect",
                    required: true,
                    dataGroup: "content",
                    maxFree: 6,
                    helperText: "Inicio + 5 páginas incluidas. Cada página adicional tiene costo extra",
                    options: [
                        { value: "inicio", label: "Página de Inicio" },
                        { value: "catalogo", label: "Catálogo / Tienda" },
                        { value: "producto_detalle", label: "Página de Producto" },
                        { value: "carrito", label: "Carrito de Compras" },
                        { value: "checkout", label: "Checkout / Pago" },
                        { value: "cuenta_usuario", label: "Mi Cuenta / Panel de Usuario" },
                        { value: "nosotros", label: "Nosotros / Quiénes somos" },
                        { value: "contacto", label: "Contacto" },
                        { value: "blog", label: "Blog / Noticias" },
                        { value: "faq", label: "Preguntas Frecuentes (FAQ)" },
                        { value: "politicas", label: "Políticas (privacidad, devoluciones, envíos)" },
                        { value: "tracking_pedidos", label: "Seguimiento de Pedidos" },
                    ],
                },
                {
                    id: "pagesDescription",
                    label: "¿Necesitas alguna página adicional?",
                    type: "textarea",
                    placeholder: "Ej: Una página de mayoristas, una landing de ofertas flash...",
                    required: false,
                    dataGroup: "content",
                    helperText: "Describe cualquier página especial que necesites",
                },
            ],
        },

        // ═══════════════════════════════════════════════════════
        // PASO 5 — Pagos y Facturación
        // ═══════════════════════════════════════════════════════
        {
            id: "payments",
            title: "Pagos y Facturación",
            description: "¿Cómo recibirás los pagos de tus clientes?",
            icon: "CreditCard",
            fields: [
                {
                    id: "paymentMethods",
                    label: "Métodos de pago que deseas aceptar",
                    type: "multiselect",
                    required: true,
                    dataGroup: "extra",
                    helperText: "Tú registras tus propias cuentas en las pasarelas — nosotros las integramos en tu tienda",
                    options: [
                        { value: "transbank_webpay", label: "Transbank (Webpay Plus)" },
                        { value: "mercadopago", label: "MercadoPago" },
                        { value: "transferencia_bancaria", label: "Transferencia bancaria manual" },
                        { value: "contra_entrega", label: "Pago contra entrega" },
                        { value: "otro_medio", label: "Otro medio de pago" },
                    ],
                },
                {
                    id: "paymentAccountStatus",
                    label: "¿Ya tienes cuenta en las pasarelas seleccionadas?",
                    type: "radio",
                    required: true,
                    dataGroup: "extra",
                    helperText: "La cuenta es tuya — tú la creas y administras, nosotros solo la conectamos a tu tienda",
                    options: [
                        { value: "ya_tengo_cuentas", label: "Sí, ya tengo mis cuentas creadas" },
                        { value: "necesito_registrarme", label: "No, necesito registrarme (lo haré yo)" },
                        { value: "no_se", label: "No estoy seguro, necesito orientación" },
                    ],
                },
                {
                    id: "needsInvoicing",
                    label: "¿Necesitas facturación electrónica (boletas/facturas)?",
                    type: "radio",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Integración con SII o sistema de facturación",
                    options: [
                        { value: "si", label: "Sí, necesito emitir boletas/facturas" },
                        { value: "no", label: "No por ahora" },
                        { value: "no_se", label: "No estoy seguro" },
                    ],
                },
                {
                    id: "currencies",
                    label: "¿En qué monedas quieres vender?",
                    type: "multiselect",
                    required: false,
                    dataGroup: "extra",
                    options: [
                        { value: "clp", label: "Pesos Chilenos (CLP)" },
                        { value: "usd", label: "Dólares (USD)" },
                        { value: "ambas", label: "Multi-moneda (CLP + USD)" },
                    ],
                },
                {
                    id: "paymentNotes",
                    label: "Notas adicionales sobre pagos",
                    type: "textarea",
                    placeholder: "Ej: Quiero ofrecer pago en cuotas, acepto crypto, etc.",
                    required: false,
                    dataGroup: "extra",
                },
            ],
        },

        // ═══════════════════════════════════════════════════════
        // PASO 6 — Envíos y Logística
        // ═══════════════════════════════════════════════════════
        {
            id: "shipping",
            title: "Envíos y Logística",
            description: "¿Cómo entregarás los productos a tus clientes?",
            icon: "Truck",
            fields: [
                {
                    id: "shippingModel",
                    label: "¿Cómo quieres calcular el costo de envío?",
                    type: "select",
                    required: true,
                    dataGroup: "extra",
                    helperText: "Tú defines los precios y zonas — nosotros lo implementamos en la tienda",
                    options: [
                        { value: "tarifa_plana", label: "Tarifa plana (mismo precio para todos)" },
                        { value: "por_zona_distancia", label: "Por zona o distancia (tú defines los rangos y precios)" },
                        { value: "gratis_sobre_monto", label: "Gratis sobre cierto monto de compra" },
                        { value: "retiro_en_tienda", label: "Solo retiro en tienda / local" },
                        { value: "solo_digital", label: "No necesito (productos 100% digitales)" },
                    ],
                },
                {
                    id: "shippingZones",
                    label: "¿A qué zonas quieres despachar?",
                    type: "multiselect",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Puedes definir distintos precios por zona después",
                    options: [
                        { value: "local_misma_ciudad", label: "Local (misma ciudad)" },
                        { value: "regional", label: "Regional (misma región)" },
                        { value: "nacional", label: "Nacional (todo Chile)" },
                        { value: "internacional", label: "Internacional" },
                    ],
                },
                {
                    id: "freeShippingThreshold",
                    label: "Monto mínimo para envío gratis (si aplica)",
                    type: "text",
                    placeholder: "Ej: 30000 (en pesos chilenos)",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Deja en blanco si no ofreces envío gratis",
                },
                {
                    id: "handlesOwnShipping",
                    label: "¿Quién maneja los envíos?",
                    type: "radio",
                    required: false,
                    dataGroup: "extra",
                    options: [
                        { value: "si_propio", label: "Yo mismo (envío propio / delivery)" },
                        { value: "courier_externo", label: "Un courier / empresa de envíos" },
                        { value: "ambos", label: "Ambos (propio + courier según zona)" },
                    ],
                },
                {
                    id: "shippingNotes",
                    label: "Detalles adicionales sobre envíos",
                    type: "textarea",
                    placeholder: "Ej: Envío gratis en Región Metropolitana sobre $30.000, resto de Chile $5.990...",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Describe tus tarifas por zona, tiempos estimados, restricciones, etc.",
                },
            ],
        },

        // ═══════════════════════════════════════════════════════
        // PASO 7 — Clientes y Cuentas
        // ═══════════════════════════════════════════════════════
        {
            id: "customers",
            title: "Clientes y Cuentas",
            description: "¿Cómo manejarás las cuentas de tus compradores?",
            icon: "Users",
            fields: [
                {
                    id: "accountSystem",
                    label: "Sistema de cuentas de usuario",
                    type: "radio",
                    required: true,
                    dataGroup: "extra",
                    helperText: "Recomendamos 'ambos' para máxima flexibilidad — el tracking de pedidos funciona mejor con cuenta",
                    options: [
                        { value: "registro_completo", label: "Solo registro (los clientes deben crear cuenta)" },
                        { value: "solo_invitado", label: "Solo invitado (compra sin registro)" },
                        { value: "ambos_registro_e_invitado", label: "Ambos: registro completo + compra como invitado" },
                    ],
                },
                {
                    id: "guestTrackingMethod",
                    label: "¿Cómo hacen seguimiento los clientes invitados?",
                    type: "select",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Solo aplica si permites compra como invitado",
                    options: [
                        { value: "por_email", label: "Reciben actualizaciones por email" },
                        { value: "por_numero_pedido", label: "Ingresan nº de pedido + email en la web" },
                        { value: "sin_tracking_invitado", label: "Sin seguimiento para invitados" },
                    ],
                },
                {
                    id: "customerFeatures",
                    label: "Funcionalidades para clientes registrados",
                    type: "multiselect",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Funciones adicionales para los usuarios que crean cuenta",
                    options: [
                        { value: "historial_pedidos", label: "Historial de pedidos" },
                        { value: "direcciones_guardadas", label: "Direcciones guardadas" },
                        { value: "lista_deseos", label: "Lista de deseos / Wishlist" },
                        { value: "puntos_fidelidad", label: "Programa de puntos / Fidelidad" },
                        { value: "referidos", label: "Sistema de referidos" },
                    ],
                },
                {
                    id: "inventoryLevel",
                    label: "¿Qué nivel de control de inventario necesitas?",
                    type: "select",
                    required: true,
                    dataGroup: "extra",
                    helperText: "Básico: muestra stock disponible. Avanzado: alertas de stock bajo, stock por variante, oculta agotados automáticamente",
                    options: [
                        { value: "sin_control", label: "Sin control (siempre disponible)" },
                        { value: "stock_basico", label: "Básico (muestra disponibilidad y agotados)" },
                        { value: "stock_avanzado", label: "Avanzado (alertas, stock por variante, gestión completa)" },
                    ],
                },
                {
                    id: "customerNotes",
                    label: "Notas adicionales sobre clientes",
                    type: "textarea",
                    placeholder: "Ej: Quiero que los mayoristas tengan precios distintos, necesito aprobación manual de cuentas...",
                    required: false,
                    dataGroup: "extra",
                },
            ],
        },

        // ═══════════════════════════════════════════════════════
        // PASO 8 — Diseño Visual
        // ═══════════════════════════════════════════════════════
        {
            id: "design",
            title: "Diseño Visual",
            description: "¿Cómo quieres que se vea tu tienda?",
            icon: "Palette",
            fields: [
                {
                    id: "designStyle",
                    label: "Estilo visual de la tienda",
                    type: "select",
                    required: true,
                    dataGroup: "design",
                    options: [
                        { value: "moderno", label: "Moderno y limpio" },
                        { value: "elegante", label: "Elegante y sofisticado" },
                        { value: "minimalista", label: "Minimalista" },
                        { value: "corporativo", label: "Corporativo / Profesional" },
                        { value: "creativo", label: "Creativo y colorido" },
                        { value: "oscuro", label: "Dark mode / Oscuro" },
                        { value: "calido", label: "Cálido y acogedor" },
                        { value: "no_se", label: "No sé, a criterio del diseñador" },
                    ],
                },
                {
                    id: "primaryColor",
                    label: "Color principal de la tienda",
                    type: "color",
                    required: true,
                    dataGroup: "design",
                    helperText: "El color predominante de tu marca",
                },
                {
                    id: "secondaryColor",
                    label: "Color secundario (opcional)",
                    type: "color",
                    required: false,
                    dataGroup: "design",
                },
                {
                    id: "accentColor",
                    label: "Color de acento para botones de compra",
                    type: "color",
                    required: false,
                    dataGroup: "design",
                    helperText: "Color para los botones 'Agregar al carrito', 'Comprar ahora', etc.",
                },
                {
                    id: "referenceUrls",
                    label: "Tiendas o sitios que te gusten como referencia",
                    type: "textarea",
                    placeholder: "Ej: zara.com, nike.com, alguna tienda chilena que te guste...",
                    required: false,
                    dataGroup: "design",
                },
            ],
        },

        // ═══════════════════════════════════════════════════════
        // PASO 9 — Contenido
        // ═══════════════════════════════════════════════════════
        {
            id: "content",
            title: "Contenido",
            description: "¿Qué material tienes listo para tu tienda?",
            icon: "FileText",
            fields: [
                {
                    id: "hasLogo",
                    label: "¿Tienes logo?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, tengo mi logo listo" },
                        { value: "no_necesito", label: "No tengo, necesito que me lo diseñen" },
                        { value: "tengo_idea", label: "No tengo, pero tengo una idea de cómo lo quiero" },
                    ],
                },
                {
                    id: "hasProductPhotos",
                    label: "¿Tienes fotos de tus productos?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    helperText: "Las fotos de producto son clave para las ventas online",
                    options: [
                        { value: "si_profesionales", label: "Sí, fotos profesionales listas" },
                        { value: "si_propias", label: "Sí, pero son fotos propias / amateur" },
                        { value: "necesito_servicio", label: "No, necesito servicio de fotografía" },
                        { value: "usare_mockups", label: "Usaré mockups / imágenes de proveedor" },
                    ],
                },
                {
                    id: "hasTexts",
                    label: "¿Tienes los textos de tu tienda?",
                    type: "radio",
                    required: false,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, tengo todo escrito" },
                        { value: "borrador", label: "Tengo un borrador / ideas" },
                        { value: "no_necesito", label: "No, necesito que los redacten" },
                    ],
                },
                {
                    id: "productDescriptionStyle",
                    label: "¿Cómo quieres las descripciones de producto?",
                    type: "select",
                    required: false,
                    dataGroup: "content",
                    helperText: "El estilo de escritura para las fichas de producto",
                    options: [
                        { value: "breve_ficha_tecnica", label: "Ficha técnica breve (specs + bullets)" },
                        { value: "descriptivo_comercial", label: "Descriptivo comercial (venta + beneficios)" },
                        { value: "storytelling", label: "Storytelling (historia + emoción)" },
                        { value: "no_se", label: "No estoy seguro, lo definen ustedes" },
                    ],
                },
                {
                    id: "additionalContent",
                    label: "Contenido o material adicional",
                    type: "textarea",
                    placeholder: "Ej: Tengo un catálogo en PDF, videos de productos, etc.",
                    required: false,
                    dataGroup: "content",
                },
            ],
        },

        // ═══════════════════════════════════════════════════════
        // PASO 10 — Marketing y SEO
        // ═══════════════════════════════════════════════════════
        {
            id: "marketing",
            title: "Marketing y SEO",
            description: "Herramientas para promocionar y posicionar tu tienda",
            icon: "Megaphone",
            fields: [
                {
                    id: "marketingFeatures",
                    label: "Herramientas de marketing que deseas",
                    type: "multiselect",
                    required: false,
                    dataGroup: "extra",
                    paidBadge: "💰 Cada herramienta de marketing tiene costo adicional",
                    helperText: "Todas las integraciones usan tus propias cuentas — nosotros solo las conectamos",
                    options: [
                        { value: "newsletter_email", label: "Email marketing / Newsletter" },
                        { value: "banners_promocionales", label: "Banners promocionales / Ofertas" },
                        { value: "analytics_tracking", label: "Analytics y tracking (Google Analytics / Meta Pixel)" },
                        { value: "seo_schema_producto", label: "SEO avanzado (schema de producto, rich snippets)" },
                        { value: "redes_sociales_shop", label: "Integración con redes sociales (Instagram/Facebook Shop)" },
                        { value: "carritos_abandonados", label: "Recuperación de carritos abandonados" },
                        { value: "codigos_descuento", label: "Códigos de descuento / Cupones" },
                        { value: "programa_referidos", label: "Programa de referidos" },
                    ],
                },
                {
                    id: "socialPlatforms",
                    label: "¿En qué plataformas quieres vender además?",
                    type: "multiselect",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Catálogos de productos sincronizados con redes sociales",
                    options: [
                        { value: "instagram_shopping", label: "Instagram Shopping" },
                        { value: "facebook_shop", label: "Facebook Shop" },
                        { value: "tiktok_shop", label: "TikTok Shop" },
                        { value: "google_shopping", label: "Google Shopping" },
                        { value: "pinterest", label: "Pinterest" },
                    ],
                },
                {
                    id: "seoLevel",
                    label: "¿Qué nivel de SEO necesitas?",
                    type: "select",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Básico: meta tags + sitemap. Avanzado: schema de producto, rich snippets, SEO técnico",
                    options: [
                        { value: "basico", label: "Básico (meta tags, sitemap, títulos)" },
                        { value: "avanzado", label: "Avanzado (schema de producto, rich snippets, SEO técnico)" },
                        { value: "seo_no_necesito", label: "No necesito por ahora" },
                    ],
                },
                {
                    id: "marketingNotes",
                    label: "Notas adicionales sobre marketing",
                    type: "textarea",
                    placeholder: "Ej: Ya tengo Google Analytics configurado, quiero integrar Mailchimp...",
                    required: false,
                    dataGroup: "extra",
                },
            ],
        },

        // ═══════════════════════════════════════════════════════
        // PASO 11 — Extras y Entrega
        // ═══════════════════════════════════════════════════════
        {
            id: "extras",
            title: "Extras y Entrega",
            description: "Funcionalidades adicionales y plazos",
            icon: "Sparkles",
            fields: [
                {
                    id: "ecommerceFeatures",
                    label: "Funcionalidades extra para tu tienda",
                    type: "multiselect",
                    required: false,
                    dataGroup: "extra",
                    paidBadge: "💰 Cada funcionalidad extra tiene costo adicional",
                    helperText: "Agrega las funcionalidades que necesites",
                    options: [
                        { value: "resenas_valoraciones", label: "Reseñas y valoraciones de productos" },
                        { value: "comparador_productos", label: "Comparador de productos" },
                        { value: "zoom_producto", label: "Zoom de imagen de producto" },
                        { value: "productos_relacionados", label: "Productos relacionados / Recomendaciones" },
                        { value: "filtros_avanzados", label: "Filtros avanzados (precio, color, talla, marca...)" },
                        { value: "busqueda_inteligente", label: "Búsqueda inteligente con autocompletado" },
                        { value: "notificaciones_stock", label: "Notificarme cuando haya stock" },
                        { value: "chat_en_vivo", label: "Chat en vivo / Soporte" },
                        { value: "multi_idioma", label: "Multi-idioma (ES/EN)" },
                        { value: "dark_mode", label: "Modo oscuro / claro" },
                        { value: "pwa_app_movil", label: "PWA / App móvil (instalable)" },
                    ],
                },
                {
                    id: "hasDomain",
                    label: "¿Ya tienes un dominio (ej: mitienda.cl)?",
                    type: "radio",
                    required: false,
                    dataGroup: "extra",
                    options: [
                        { value: "si_tengo", label: "Sí, ya tengo dominio" },
                        { value: "necesito", label: "No, necesito uno" },
                        { value: "no_se", label: "No estoy seguro" },
                    ],
                },
                {
                    id: "domainName",
                    label: "¿Cuál es tu dominio?",
                    type: "text",
                    placeholder: "Ej: mitienda.cl",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Solo si ya tienes uno registrado",
                },
                {
                    id: "deadline",
                    label: "¿Para cuándo necesitas la tienda?",
                    type: "select",
                    required: false,
                    dataGroup: "extra",
                    options: [
                        { value: "urgente", label: "Lo antes posible (esta semana)" },
                        { value: "pronto", label: "En 1-2 semanas" },
                        { value: "normal", label: "En 2-4 semanas" },
                        { value: "sin_prisa", label: "Sin prisa, cuando esté listo" },
                    ],
                },
                {
                    id: "additionalNotes",
                    label: "¿Algo más que debamos saber?",
                    type: "textarea",
                    placeholder: "Ej: Tengo una tienda en Instagram que quiero migrar, necesito integración con mi sistema de inventario...",
                    required: false,
                    dataGroup: "extra",
                },
            ],
        },
    ],
};
