import { BriefingTypeConfig } from "@/types/briefing";

export const landingConfig: BriefingTypeConfig = {
    id: "landing",
    type: "LANDING",
    label: "Landing Page",
    description: "Página de aterrizaje profesional para captar clientes y mostrar tu negocio",
    icon: "Rocket",
    enabled: true,
    steps: [
        {
            id: "identity",
            title: "Tu Negocio",
            description: "Cuéntanos sobre ti y tu negocio",
            icon: "Building2",
            fields: [
                {
                    id: "clientName",
                    label: "Tu nombre y apellido",
                    type: "text",
                    placeholder: "Ej: Juan Pérez",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "businessName",
                    label: "Nombre de tu negocio o marca",
                    type: "text",
                    placeholder: "Ej: Panadería Don Juan",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "industry",
                    label: "Rubro o industria",
                    type: "select",
                    required: true,
                    dataGroup: "contact",
                    options: [
                        { value: "gastronomia", label: "Gastronomía / Restaurante" },
                        { value: "salud", label: "Salud / Medicina" },
                        { value: "belleza", label: "Belleza / Estética" },
                        { value: "educacion", label: "Educación / Cursos" },
                        { value: "tecnologia", label: "Tecnología / Software" },
                        { value: "inmobiliaria", label: "Inmobiliaria / Bienes raíces" },
                        { value: "legal", label: "Legal / Abogados" },
                        { value: "fitness", label: "Fitness / Deporte" },
                        { value: "construccion", label: "Construcción / Remodelación" },
                        { value: "automotriz", label: "Automotriz" },
                        { value: "agricultura", label: "Agricultura / Agro" },
                        { value: "consultoria", label: "Consultoría / Asesoría" },
                        { value: "marketing", label: "Marketing / Publicidad" },
                        { value: "otro", label: "Otro" },
                    ],
                },
                {
                    id: "email",
                    label: "Correo electrónico de contacto",
                    type: "email",
                    placeholder: "Ej: juan@minegocio.cl",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "phone",
                    label: "Teléfono / WhatsApp",
                    type: "tel",
                    placeholder: "Ej: +56 9 1234 5678",
                    required: false,
                    dataGroup: "contact",
                },
                {
                    id: "instagramUrl",
                    label: "Instagram (opcional)",
                    type: "text",
                    placeholder: "Ej: @minegocio o instagram.com/minegocio",
                    required: false,
                    dataGroup: "contact",
                    helperText: "Tu perfil de Instagram para mostrarlo en la landing",
                },
                {
                    id: "facebookUrl",
                    label: "Facebook (opcional)",
                    type: "text",
                    placeholder: "Ej: facebook.com/minegocio",
                    required: false,
                    dataGroup: "contact",
                    helperText: "Tu página de Facebook",
                },
                {
                    id: "twitterUrl",
                    label: "Twitter / X (opcional)",
                    type: "text",
                    placeholder: "Ej: @minegocio o x.com/minegocio",
                    required: false,
                    dataGroup: "contact",
                    helperText: "Tu perfil de Twitter/X",
                },
            ],
        },
        {
            id: "objective",
            title: "Objetivo",
            description: "¿Qué quieres lograr con tu landing page?",
            icon: "Target",
            fields: [
                {
                    id: "mainGoal",
                    label: "Objetivo principal de la landing",
                    type: "select",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "captar_leads", label: "Captar clientes potenciales (leads)" },
                        { value: "vender_servicio", label: "Promocionar y vender un servicio" },
                        { value: "vender_producto", label: "Promocionar un producto" },
                        { value: "informar", label: "Dar a conocer mi negocio" },
                        { value: "evento", label: "Promocionar un evento" },
                        { value: "portafolio", label: "Mostrar mi portafolio / trabajo" },
                        { value: "otro", label: "Otro" },
                    ],
                },
                {
                    id: "targetAudience",
                    label: "¿Quién es tu cliente ideal?",
                    type: "textarea",
                    placeholder: "Ej: Mujeres de 25-45 años que buscan servicios de belleza en Santiago...",
                    required: true,
                    dataGroup: "content",
                    helperText: "Describe tu público objetivo: edad, género, ubicación, intereses",
                },
                {
                    id: "mainCTA",
                    label: "¿Qué acción principal quieres que tome el visitante?",
                    type: "select",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "whatsapp", label: "Contactar por WhatsApp" },
                        { value: "formulario", label: "Llenar un formulario de contacto" },
                        { value: "llamar", label: "Llamar por teléfono" },
                        { value: "agendar", label: "Agendar una cita / reunión" },
                        { value: "comprar", label: "Comprar un producto / servicio" },
                        { value: "descargar", label: "Descargar algo (PDF, catálogo, etc.)" },
                        { value: "otro", label: "Otro" },
                    ],
                },
                {
                    id: "uniqueValue",
                    label: "¿Qué te hace diferente de tu competencia?",
                    type: "textarea",
                    placeholder: "Ej: 10 años de experiencia, atención personalizada, precios competitivos...",
                    required: false,
                    dataGroup: "content",
                    helperText: "Esto nos ayuda a destacar lo que te hace especial",
                },
            ],
        },
        {
            id: "sections",
            title: "Secciones",
            description: "¿Qué secciones quieres en tu landing page?",
            icon: "LayoutGrid",
            fields: [
                {
                    id: "sections",
                    label: "Selecciona las secciones que necesitas",
                    type: "multiselect",
                    required: true,
                    dataGroup: "content",
                    maxFree: 6,
                    helperText: "Inicio + 5 secciones incluidas. Cada sección adicional tiene costo extra",
                    options: [
                        { value: "hero", label: "🎯 Hero / Banner principal" },
                        { value: "servicios", label: "💼 Servicios / Lo que ofrezco" },
                        { value: "proceso", label: "🔄 Proceso / Cómo trabajamos" },
                        { value: "sobre_mi", label: "👤 Sobre mí / Nosotros" },
                        { value: "portafolio", label: "📸 Portafolio / Galería de trabajos" },
                        { value: "testimonios", label: "⭐ Testimonios / Reseñas" },
                        { value: "equipo", label: "👥 Equipo de trabajo" },
                        { value: "precios", label: "💰 Precios / Planes" },
                        { value: "faq", label: "❓ Preguntas frecuentes (FAQ)" },
                        { value: "blog", label: "📝 Blog / Noticias" },
                        { value: "contacto", label: "📞 Formulario de contacto" },
                        { value: "ubicacion", label: "📍 Mapa / Ubicación" },
                        { value: "estadisticas", label: "📊 Cifras / Estadísticas" },
                        { value: "clientes", label: "🏢 Logos de clientes" },
                    ],
                },
                {
                    id: "sectionNotes",
                    label: "¿Alguna nota sobre las secciones?",
                    type: "textarea",
                    placeholder: "Ej: Quiero que los testimonios sean de Google Maps, que el portafolio tenga antes/después...",
                    required: false,
                    dataGroup: "content",
                },
            ],
        },
        {
            id: "design",
            title: "Diseño",
            description: "¿Cómo quieres que se vea tu landing page?",
            icon: "Palette",
            fields: [
                {
                    id: "designStyle",
                    label: "Estilo visual que prefieres",
                    type: "select",
                    required: true,
                    dataGroup: "design",
                    options: [
                        { value: "moderno", label: "🔷 Moderno y limpio" },
                        { value: "elegante", label: "✨ Elegante y sofisticado" },
                        { value: "minimalista", label: "⬜ Minimalista" },
                        { value: "corporativo", label: "🏢 Corporativo / Profesional" },
                        { value: "creativo", label: "🎨 Creativo y colorido" },
                        { value: "oscuro", label: "🌙 Dark mode / Oscuro" },
                        { value: "calido", label: "☀️ Cálido y acogedor" },
                        { value: "no_se", label: "🤷 No estoy seguro, decídanlo ustedes" },
                    ],
                },
                {
                    id: "primaryColor",
                    label: "Color principal de tu marca",
                    type: "color",
                    required: false,
                    dataGroup: "design",
                    helperText: "Si tienes colores de marca, selecciona el principal",
                },
                {
                    id: "secondaryColor",
                    label: "Color secundario (opcional)",
                    type: "color",
                    required: false,
                    dataGroup: "design",
                },
                {
                    id: "referenceUrls",
                    label: "¿Hay alguna página web que te guste como referencia?",
                    type: "textarea",
                    placeholder: "Pega los links de páginas que te gusten...\nEj: https://ejemplo.com",
                    required: false,
                    dataGroup: "design",
                    helperText: "Nos ayuda a entender el estilo que buscas",
                },
            ],
        },
        {
            id: "content",
            title: "Contenido",
            description: "¿Qué material tienes listo?",
            icon: "FileText",
            fields: [
                {
                    id: "hasLogo",
                    label: "¿Tienes logo?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, tengo logo listo" },
                        { value: "no_necesito", label: "No tengo, pero lo necesito" },
                        { value: "no_no_necesito", label: "No tengo y no lo necesito por ahora" },
                    ],
                },
                {
                    id: "hasPhotos",
                    label: "¿Tienes fotos propias de tu negocio/productos?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, tengo fotos propias" },
                        { value: "algunas", label: "Tengo algunas, pero necesitaría más" },
                        { value: "no", label: "No tengo, usen fotos de stock" },
                    ],
                },
                {
                    id: "hasTexts",
                    label: "¿Tienes los textos escritos para la página?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, están listos" },
                        { value: "borrador", label: "Tengo un borrador / ideas" },
                        { value: "no", label: "No, necesito ayuda con los textos" },
                    ],
                },
                {
                    id: "additionalContent",
                    label: "¿Necesitas algo extra en tu landing?",
                    type: "textarea",
                    placeholder: "Ej: Catálogo PDF descargable, sección de video, integración con agenda, enlaces a marketplaces, botón de descarga...",
                    required: false,
                    dataGroup: "content",
                    helperText: "Describe cualquier funcionalidad o contenido especial que necesites y lo verás reflejado en la preview",
                },
            ],
        },
        {
            id: "extras",
            title: "Extras y Entrega",
            description: "Funcionalidades adicionales y plazos",
            icon: "Settings",
            fields: [
                {
                    id: "features",
                    label: "Funcionalidades adicionales que necesitas",
                    type: "multiselect",
                    required: false,
                    dataGroup: "extra",
                    options: [
                        { value: "whatsapp_button", label: "💬 Redes sociales y WhatsApp flotante" },
                        { value: "google_maps", label: "📍 Google Maps integrado" },
                        { value: "formulario_contacto", label: "📝 Formulario de contacto" },
                        { value: "formulario_avanzado", label: "📋 Formulario avanzado (más campos)" },
                        { value: "animaciones", label: "✨ Animaciones y efectos" },
                        { value: "multiidioma", label: "🌐 Multi-idioma (ES/EN)" },
                        { value: "agenda", label: "📅 Integración con agenda (Calendly)" },
                        { value: "descargables", label: "📥 Descargables (PDF / Catálogo)" },
                        { value: "analytics", label: "📊 Google Analytics" },
                        { value: "seo", label: "🔍 Optimización SEO" },
                    ],
                },
                {
                    id: "hasDomain",
                    label: "¿Tienes dominio web?",
                    type: "radio",
                    required: true,
                    dataGroup: "extra",
                    options: [
                        { value: "si", label: "Sí, ya tengo uno" },
                        { value: "necesito", label: "No, necesito uno" },
                        { value: "no_se", label: "No sé qué es un dominio" },
                    ],
                },
                {
                    id: "domainName",
                    label: "Si tienes dominio, ¿cuál es?",
                    type: "text",
                    placeholder: "Ej: www.minegocio.cl",
                    required: false,
                    dataGroup: "extra",
                },
                {
                    id: "deadline",
                    label: "¿Para cuándo necesitas la página?",
                    type: "select",
                    required: true,
                    dataGroup: "extra",
                    options: [
                        { value: "urgente", label: "🔥 Esta semana" },
                        { value: "pronto", label: "⚡ En 1-2 semanas" },
                        { value: "normal", label: "📅 En 2-3 semanas" },
                        { value: "sin_prisa", label: "🐢 Sin prisa, cuando esté listo" },
                    ],
                },
                {
                    id: "additionalNotes",
                    label: "¿Algo más que debamos saber sobre tu proyecto?",
                    type: "textarea",
                    placeholder: "Ej: Tengo un catálogo que quiero subir, necesito que se vea igual a otra web, tengo textos listos en un documento...",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Cualquier detalle extra que nos ayude a entregar exactamente lo que necesitas",
                },
            ],
        },
    ],
};
