import { BriefingTypeConfig } from "@/types/briefing";

export const webCorporativaConfig: BriefingTypeConfig = {
    id: "web-corporativa",
    type: "WEB_CORPORATIVA",
    label: "Web Corporativa",
    description: "Sitio web completo con múltiples páginas para tu negocio",
    icon: "Building2",
    enabled: true,
    steps: [
        {
            id: "identity",
            title: "Tu Negocio",
            description: "Cuéntanos sobre ti y tu negocio",
            icon: "Building2",
            fields: [
                {
                    id: "clientName",
                    label: "Tu nombre y apellido",
                    type: "text",
                    placeholder: "Ej: Juan Pérez",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "businessName",
                    label: "Nombre de tu negocio o marca",
                    type: "text",
                    placeholder: "Ej: Consultoría López & Asociados",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "industry",
                    label: "Rubro o industria",
                    type: "select",
                    required: true,
                    dataGroup: "contact",
                    options: [
                        { value: "gastronomia", label: "Gastronomía / Restaurante" },
                        { value: "salud", label: "Salud / Medicina" },
                        { value: "belleza", label: "Belleza / Estética" },
                        { value: "educacion", label: "Educación / Cursos" },
                        { value: "tecnologia", label: "Tecnología / Software" },
                        { value: "inmobiliaria", label: "Inmobiliaria / Bienes raíces" },
                        { value: "legal", label: "Legal / Abogados" },
                        { value: "fitness", label: "Fitness / Deporte" },
                        { value: "construccion", label: "Construcción / Remodelación" },
                        { value: "automotriz", label: "Automotriz" },
                        { value: "agricultura", label: "Agricultura / Agro" },
                        { value: "consultoria", label: "Consultoría / Asesoría" },
                        { value: "marketing", label: "Marketing / Publicidad" },
                        { value: "otro", label: "Otro" },
                    ],
                },
                {
                    id: "email",
                    label: "Correo electrónico de contacto",
                    type: "email",
                    placeholder: "Ej: contacto@miempresa.cl",
                    required: true,
                    dataGroup: "contact",
                },
                {
                    id: "phone",
                    label: "Teléfono / WhatsApp",
                    type: "tel",
                    placeholder: "Ej: +56 9 1234 5678",
                    required: false,
                    dataGroup: "contact",
                },
                {
                    id: "instagramUrl",
                    label: "Instagram (opcional)",
                    type: "text",
                    placeholder: "Ej: @miempresa o instagram.com/miempresa",
                    required: false,
                    dataGroup: "contact",
                    helperText: "Tu perfil de Instagram para mostrarlo en el sitio",
                },
                {
                    id: "facebookUrl",
                    label: "Facebook (opcional)",
                    type: "text",
                    placeholder: "Ej: facebook.com/miempresa",
                    required: false,
                    dataGroup: "contact",
                    helperText: "Tu página de Facebook",
                },
                {
                    id: "twitterUrl",
                    label: "Twitter / X (opcional)",
                    type: "text",
                    placeholder: "Ej: @miempresa o x.com/miempresa",
                    required: false,
                    dataGroup: "contact",
                    helperText: "Tu perfil de Twitter/X",
                },
            ],
        },
        {
            id: "objective",
            title: "Objetivo",
            description: "¿Qué quieres lograr con tu sitio web?",
            icon: "Target",
            fields: [
                {
                    id: "siteObjective",
                    label: "Objetivo principal del sitio web",
                    type: "select",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "presencia_digital", label: "Tener presencia digital profesional" },
                        { value: "captar_clientes", label: "Captar clientes y generar contactos" },
                        { value: "mostrar_portafolio", label: "Mostrar mi portafolio / proyectos" },
                        { value: "informar_servicios", label: "Informar sobre mis servicios en detalle" },
                        { value: "generar_confianza", label: "Generar confianza y credibilidad" },
                        { value: "otro", label: "Otro" },
                    ],
                },
                {
                    id: "targetAudience",
                    label: "¿Quién es tu cliente ideal?",
                    type: "textarea",
                    placeholder: "Ej: Empresas medianas de Santiago que buscan consultoría en transformación digital...",
                    required: true,
                    dataGroup: "content",
                    helperText: "Describe tu público objetivo: edad, género, ubicación, intereses",
                },
                {
                    id: "mainCTA",
                    label: "¿Qué acción principal quieres que tome el visitante?",
                    type: "select",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "whatsapp", label: "Contactar por WhatsApp" },
                        { value: "formulario", label: "Llenar un formulario de contacto" },
                        { value: "llamar", label: "Llamar por teléfono" },
                        { value: "agendar", label: "Agendar una cita / reunión" },
                        { value: "comprar", label: "Solicitar cotización" },
                        { value: "otro", label: "Otro" },
                    ],
                },
                {
                    id: "uniqueValue",
                    label: "¿Qué te hace diferente de tu competencia?",
                    type: "textarea",
                    placeholder: "Ej: 15 años de experiencia, equipo multidisciplinario, metodología propia...",
                    required: false,
                    dataGroup: "content",
                    helperText: "Esto nos ayuda a destacar lo que te hace especial en cada página",
                },
            ],
        },
        {
            id: "pages",
            title: "Páginas",
            description: "¿Qué páginas necesita tu sitio web?",
            icon: "LayoutGrid",
            fields: [
                {
                    id: "pages",
                    label: "Selecciona las páginas que necesitas",
                    type: "multiselect",
                    required: true,
                    dataGroup: "content",
                    maxFree: 6,
                    helperText: "Inicio + 5 páginas incluidas. Cada página adicional tiene costo extra",
                    options: [
                        { value: "inicio", label: "🏠 Inicio (hero, intro, destacados)" },
                        { value: "servicios", label: "💼 Servicios / Productos (detalle por servicio)" },
                        { value: "nosotros", label: "👥 Nosotros / Quiénes Somos" },
                        { value: "contacto", label: "📞 Contacto (formulario, mapa, datos)" },
                        { value: "portafolio", label: "📸 Portafolio / Experiencias / Proyectos" },
                        { value: "galeria", label: "🖼️ Galería de imágenes" },
                        { value: "blog", label: "📝 Blog / Noticias" },
                        { value: "faq", label: "❓ Preguntas Frecuentes (FAQ)" },
                        { value: "casos_exito", label: "🏆 Casos de Éxito / Testimonios" },
                        { value: "precios", label: "💰 Precios / Planes" },
                    ],
                },
                {
                    id: "pagesDescription",
                    label: "Describe brevemente qué quieres en cada página",
                    type: "textarea",
                    placeholder: "Ej:\n- Inicio: Banner con frase impactante y nuestros 3 servicios principales\n- Servicios: 5 servicios con descripción detallada e imágenes\n- Nosotros: Historia de la empresa, misión, visión y equipo...",
                    required: false,
                    dataGroup: "content",
                    helperText: "Mientras más detalle nos des, mejor resultado obtendrás",
                },
            ],
        },
        {
            id: "design",
            title: "Diseño",
            description: "¿Cómo quieres que se vea tu sitio web?",
            icon: "Palette",
            fields: [
                {
                    id: "designStyle",
                    label: "Estilo visual que prefieres",
                    type: "select",
                    required: true,
                    dataGroup: "design",
                    options: [
                        { value: "moderno", label: "🔷 Moderno y limpio" },
                        { value: "elegante", label: "✨ Elegante y sofisticado" },
                        { value: "minimalista", label: "⬜ Minimalista" },
                        { value: "corporativo", label: "🏢 Corporativo / Profesional" },
                        { value: "creativo", label: "🎨 Creativo y colorido" },
                        { value: "oscuro", label: "🌙 Dark mode / Oscuro" },
                        { value: "calido", label: "☀️ Cálido y acogedor" },
                        { value: "no_se", label: "🤷 No estoy seguro, decídanlo ustedes" },
                    ],
                },
                {
                    id: "primaryColor",
                    label: "Color principal de tu marca",
                    type: "color",
                    required: false,
                    dataGroup: "design",
                    helperText: "Si tienes colores de marca, selecciona el principal",
                },
                {
                    id: "secondaryColor",
                    label: "Color secundario (opcional)",
                    type: "color",
                    required: false,
                    dataGroup: "design",
                },
                {
                    id: "referenceUrls",
                    label: "¿Hay alguna página web que te guste como referencia?",
                    type: "textarea",
                    placeholder: "Pega los links de páginas que te gusten...\nEj: https://ejemplo.com",
                    required: false,
                    dataGroup: "design",
                    helperText: "Nos ayuda a entender el estilo que buscas",
                },
            ],
        },
        {
            id: "content",
            title: "Contenido",
            description: "¿Qué material tienes listo?",
            icon: "FileText",
            fields: [
                {
                    id: "hasLogo",
                    label: "¿Tienes logo?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, tengo logo listo" },
                        { value: "no_necesito", label: "No tengo, pero lo necesito" },
                        { value: "no_no_necesito", label: "No tengo y no lo necesito por ahora" },
                    ],
                },
                {
                    id: "hasPhotos",
                    label: "¿Tienes fotos propias de tu negocio/productos?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, tengo fotos propias" },
                        { value: "algunas", label: "Tengo algunas, pero necesitaría más" },
                        { value: "no", label: "No tengo, usen fotos de stock" },
                    ],
                },
                {
                    id: "hasTexts",
                    label: "¿Tienes los textos escritos para las páginas?",
                    type: "radio",
                    required: true,
                    dataGroup: "content",
                    options: [
                        { value: "si", label: "Sí, están listos" },
                        { value: "borrador", label: "Tengo un borrador / ideas" },
                        { value: "no", label: "No, necesito ayuda con los textos" },
                    ],
                },
                {
                    id: "additionalContent",
                    label: "¿Necesitas algo extra en tu sitio web?",
                    type: "textarea",
                    placeholder: "Ej: Catálogo PDF descargable, sección de videos, integración con CRM, enlaces a marketplaces...",
                    required: false,
                    dataGroup: "content",
                    helperText: "Describe cualquier funcionalidad o contenido especial que necesites",
                },
            ],
        },
        {
            id: "extras",
            title: "Extras y Entrega",
            description: "Funcionalidades adicionales y plazos",
            icon: "Settings",
            fields: [
                {
                    id: "features",
                    label: "Funcionalidades adicionales que necesitas",
                    type: "multiselect",
                    required: false,
                    dataGroup: "extra",
                    options: [
                        { value: "whatsapp_button", label: "💬 Redes sociales y WhatsApp flotante" },
                        { value: "google_maps", label: "📍 Google Maps integrado" },
                        { value: "formulario_contacto", label: "📝 Formulario de contacto" },
                        { value: "formulario_avanzado", label: "📋 Formulario avanzado (más campos)" },
                        { value: "animaciones", label: "✨ Animaciones y efectos" },
                        { value: "multiidioma", label: "🌐 Multi-idioma (ES/EN)" },
                        { value: "agenda", label: "📅 Integración con agenda (Calendly)" },
                        { value: "descargables", label: "📥 Descargables (PDF / Catálogo)" },
                        { value: "analytics", label: "📊 Google Analytics" },
                        { value: "seo", label: "🔍 Optimización SEO" },
                        { value: "dark_mode", label: "🌙 Modo oscuro / claro toggle" },
                        { value: "buscador", label: "🔎 Buscador en el sitio" },
                        { value: "chat_en_vivo", label: "💬 Chat en vivo" },
                    ],
                },
                {
                    id: "hasDomain",
                    label: "¿Tienes dominio web?",
                    type: "radio",
                    required: true,
                    dataGroup: "extra",
                    options: [
                        { value: "si", label: "Sí, ya tengo uno" },
                        { value: "necesito", label: "No, necesito uno" },
                        { value: "no_se", label: "No sé qué es un dominio" },
                    ],
                },
                {
                    id: "domainName",
                    label: "Si tienes dominio, ¿cuál es?",
                    type: "text",
                    placeholder: "Ej: www.miempresa.cl",
                    required: false,
                    dataGroup: "extra",
                },
                {
                    id: "deadline",
                    label: "¿Para cuándo necesitas el sitio web?",
                    type: "select",
                    required: true,
                    dataGroup: "extra",
                    options: [
                        { value: "urgente", label: "🔥 Esta semana" },
                        { value: "pronto", label: "⚡ En 1-2 semanas" },
                        { value: "normal", label: "📅 En 2-4 semanas" },
                        { value: "sin_prisa", label: "🐢 Sin prisa, cuando esté listo" },
                    ],
                },
                {
                    id: "additionalNotes",
                    label: "¿Algo más que debamos saber sobre tu proyecto?",
                    type: "textarea",
                    placeholder: "Ej: Tenemos un sitio actual que queremos rediseñar, necesitamos migración de contenido, queremos un blog con categorías...",
                    required: false,
                    dataGroup: "extra",
                    helperText: "Cualquier detalle extra que nos ayude a entregar exactamente lo que necesitas",
                },
            ],
        },
    ],
};
